version: "3.8"

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: telegram-bot:2.0.0
    restart: always
    volumes:
      - localDB:/usr/src/app/localDB:rw
    env_file:
      - .env
volumes:
  localDB:
