version: '3.8'

services:
  selenium-chrome:
    image: selenium/standalone-chrome:3.141.59
    restart: always
    volumes:
      - downloads:/home/seluser/Downloads:rw
    ports:
      - '4444:4444'
    networks:
      - telegram-bot
  telegram-bot:
    image: telegram-bot:1.0.0
    restart: always
    volumes:
      - downloads:/usr/src/app/src/Downloads:rw
    networks:
      - telegram-bot
    depends_on:
      - selenium-chrome
    env_file:
      - .env

networks:
  telegram-bot:
    driver: overlay

volumes:
  downloads:
