version: "3.8"

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: telegram-bot:2.0.1
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
    volumes:
      - localDB:/usr/src/app/localDB:rw
    env_file:
      - .env
volumes:
  localDB:
